select * from rpm_future_retail where action_date in ('23-NOV-22','29-NOV-22') and (item,location) in (select item,location from rpm_promo_item_loc_expl);

create table rpm_future_retail_to_Copy as
select * from rpm_future_retail rfr where action_date between '21-NOV-22' and '30-NOV-22' 
    and exists (select 1 from rpm_promo_item_loc_expl rpil where rpil.item = rfr.item and rpil.location = rfr.location);

select * from rpm_future_retail_to_Copy;

select * from rpm_future_retail where item = '115013639';
select * from rpm_promo_item_loc_expl where item = '115013639';

select * from all_sequences where sequence_name like 'RPM_FUTURE%'; --3203841993

select * from rpm_future_retail where FUTURE_RETAIL_ID >= '3180431993';
select * from rpm_future_retail where item = '101286445';
--RPM_FUTURE_RETAIL_SEQ.nextval


    select count (1) from rpm_future_retail_to_Copy; --22615474
    
    select min (ACTION_DATE) from rpm_future_retail_to_Copy;

    select ITEM, DEPT, CLASS, SUBCLASS, ZONE_NODE_TYPE, LOCATION, ACTION_DATE, 
           SELLING_RETAIL, SELLING_RETAIL_CURRENCY, SELLING_UOM, MULTI_UNITS, MULTI_UNIT_RETAIL, MULTI_UNIT_RETAIL_CURRENCY, MULTI_SELLING_UOM, CLEAR_EXCEPTION_PARENT_ID, CLEAR_RETAIL, CLEAR_RETAIL_CURRENCY, CLEAR_UOM, SIMPLE_PROMO_RETAIL, SIMPLE_PROMO_RETAIL_CURRENCY, SIMPLE_PROMO_UOM, ON_SIMPLE_PROMO_IND, ON_COMPLEX_PROMO_IND, PRICE_CHANGE_ID, PRICE_CHANGE_DISPLAY_ID, PC_EXCEPTION_PARENT_ID, PC_CHANGE_TYPE, PC_CHANGE_AMOUNT, PC_CHANGE_CURRENCY, PC_CHANGE_PERCENT, PC_CHANGE_SELLING_UOM, PC_NULL_MULTI_IND, PC_MULTI_UNITS, PC_MULTI_UNIT_RETAIL, PC_MULTI_UNIT_RETAIL_CURRENCY, PC_MULTI_SELLING_UOM, PC_PRICE_GUIDE_ID, CLEARANCE_ID, CLEARANCE_DISPLAY_ID, CLEAR_MKDN_INDEX, CLEAR_START_IND, CLEAR_CHANGE_TYPE, CLEAR_CHANGE_AMOUNT, CLEAR_CHANGE_CURRENCY, CLEAR_CHANGE_PERCENT, CLEAR_CHANGE_SELLING_UOM, CLEAR_PRICE_GUIDE_ID, LOC_MOVE_FROM_ZONE_ID, LOC_MOVE_TO_ZONE_ID, LOCATION_MOVE_ID, LOCK_VERSION, ITEM_PARENT, DIFF_ID, ZONE_ID, MAX_HIER_LEVEL, CUR_HIER_LEVEL 
      from rpm_future_retail_to_Copy;

    insert into rpm_future_retail_to_Copy
    select RPM_FUTURE_RETAIL_SEQ.nextval, ITEM, DEPT, CLASS, SUBCLASS, ZONE_NODE_TYPE, LOCATION, ACTION_DATE-10, 
           SELLING_RETAIL, SELLING_RETAIL_CURRENCY, SELLING_UOM, MULTI_UNITS, MULTI_UNIT_RETAIL, MULTI_UNIT_RETAIL_CURRENCY, MULTI_SELLING_UOM, CLEAR_EXCEPTION_PARENT_ID, CLEAR_RETAIL, CLEAR_RETAIL_CURRENCY, CLEAR_UOM, SIMPLE_PROMO_RETAIL, SIMPLE_PROMO_RETAIL_CURRENCY, SIMPLE_PROMO_UOM, ON_SIMPLE_PROMO_IND, ON_COMPLEX_PROMO_IND, PRICE_CHANGE_ID, PRICE_CHANGE_DISPLAY_ID, PC_EXCEPTION_PARENT_ID, PC_CHANGE_TYPE, PC_CHANGE_AMOUNT, PC_CHANGE_CURRENCY, PC_CHANGE_PERCENT, PC_CHANGE_SELLING_UOM, PC_NULL_MULTI_IND, PC_MULTI_UNITS, PC_MULTI_UNIT_RETAIL, PC_MULTI_UNIT_RETAIL_CURRENCY, PC_MULTI_SELLING_UOM, PC_PRICE_GUIDE_ID, CLEARANCE_ID, CLEARANCE_DISPLAY_ID, CLEAR_MKDN_INDEX, CLEAR_START_IND, CLEAR_CHANGE_TYPE, CLEAR_CHANGE_AMOUNT, CLEAR_CHANGE_CURRENCY, CLEAR_CHANGE_PERCENT, CLEAR_CHANGE_SELLING_UOM, CLEAR_PRICE_GUIDE_ID, LOC_MOVE_FROM_ZONE_ID, LOC_MOVE_TO_ZONE_ID, LOCATION_MOVE_ID, LOCK_VERSION, ITEM_PARENT, DIFF_ID, ZONE_ID, MAX_HIER_LEVEL, CUR_HIER_LEVEL 
      from rpm_future_retail_to_Copy;


set SERVEROUTPUT ON;
set timing on;
BEGIN
for k in 1..4 loop

  insert into rpm_future_retail (FUTURE_RETAIL_ID, ITEM, DEPT, CLASS, SUBCLASS, ZONE_NODE_TYPE, LOCATION, ACTION_DATE, SELLING_RETAIL, SELLING_RETAIL_CURRENCY, SELLING_UOM, MULTI_UNITS, MULTI_UNIT_RETAIL, MULTI_UNIT_RETAIL_CURRENCY, MULTI_SELLING_UOM, CLEAR_EXCEPTION_PARENT_ID, CLEAR_RETAIL, CLEAR_RETAIL_CURRENCY, CLEAR_UOM, SIMPLE_PROMO_RETAIL, SIMPLE_PROMO_RETAIL_CURRENCY, SIMPLE_PROMO_UOM, ON_SIMPLE_PROMO_IND, ON_COMPLEX_PROMO_IND, PRICE_CHANGE_ID, PRICE_CHANGE_DISPLAY_ID, PC_EXCEPTION_PARENT_ID, PC_CHANGE_TYPE, PC_CHANGE_AMOUNT, PC_CHANGE_CURRENCY, PC_CHANGE_PERCENT, PC_CHANGE_SELLING_UOM, PC_NULL_MULTI_IND, PC_MULTI_UNITS, PC_MULTI_UNIT_RETAIL, PC_MULTI_UNIT_RETAIL_CURRENCY, PC_MULTI_SELLING_UOM, PC_PRICE_GUIDE_ID, CLEARANCE_ID, CLEARANCE_DISPLAY_ID, CLEAR_MKDN_INDEX, CLEAR_START_IND, CLEAR_CHANGE_TYPE, CLEAR_CHANGE_AMOUNT, CLEAR_CHANGE_CURRENCY, CLEAR_CHANGE_PERCENT, CLEAR_CHANGE_SELLING_UOM, CLEAR_PRICE_GUIDE_ID, LOC_MOVE_FROM_ZONE_ID, LOC_MOVE_TO_ZONE_ID, LOCATION_MOVE_ID, LOCK_VERSION, ITEM_PARENT, DIFF_ID, ZONE_ID, MAX_HIER_LEVEL, CUR_HIER_LEVEL)
    select RPM_FUTURE_RETAIL_SEQ.nextval, ITEM, DEPT, CLASS, SUBCLASS, ZONE_NODE_TYPE, LOCATION, ACTION_DATE +120+k, 
           SELLING_RETAIL, SELLING_RETAIL_CURRENCY, SELLING_UOM, MULTI_UNITS, MULTI_UNIT_RETAIL, MULTI_UNIT_RETAIL_CURRENCY, MULTI_SELLING_UOM, CLEAR_EXCEPTION_PARENT_ID, CLEAR_RETAIL, CLEAR_RETAIL_CURRENCY, CLEAR_UOM, SIMPLE_PROMO_RETAIL, SIMPLE_PROMO_RETAIL_CURRENCY, SIMPLE_PROMO_UOM, ON_SIMPLE_PROMO_IND, ON_COMPLEX_PROMO_IND, PRICE_CHANGE_ID, PRICE_CHANGE_DISPLAY_ID, PC_EXCEPTION_PARENT_ID, PC_CHANGE_TYPE, PC_CHANGE_AMOUNT, PC_CHANGE_CURRENCY, PC_CHANGE_PERCENT, PC_CHANGE_SELLING_UOM, PC_NULL_MULTI_IND, PC_MULTI_UNITS, PC_MULTI_UNIT_RETAIL, PC_MULTI_UNIT_RETAIL_CURRENCY, PC_MULTI_SELLING_UOM, PC_PRICE_GUIDE_ID, CLEARANCE_ID, CLEARANCE_DISPLAY_ID, CLEAR_MKDN_INDEX, CLEAR_START_IND, CLEAR_CHANGE_TYPE, CLEAR_CHANGE_AMOUNT, CLEAR_CHANGE_CURRENCY, CLEAR_CHANGE_PERCENT, CLEAR_CHANGE_SELLING_UOM, CLEAR_PRICE_GUIDE_ID, LOC_MOVE_FROM_ZONE_ID, LOC_MOVE_TO_ZONE_ID, LOCATION_MOVE_ID, LOCK_VERSION, ITEM_PARENT, DIFF_ID, ZONE_ID, MAX_HIER_LEVEL, CUR_HIER_LEVEL 
      from rpm_future_retail_to_Copy;
commit;

end loop; 
EXCEPTION
   when OTHERS THEN
      dbms_output.put_line('Exception Block'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
END;
/