sudo su - oracle
cd /orabin/app/oracle/product/retail/batch
. ./batch.profile
cd /orabin/app/oracle/product/retail/batch/oracle/proc/bin
./nb_scap_report.ksh $UP 20190601 20200301 PRE /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
./nb_scap_report.ksh $UP 20190601 20200301 RESA /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
./nb_scap_report.ksh $UP 20190601 20200301 RESA_ARCHIVED /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
./nb_scap_report.ksh $UP 20190601 20200301 ROLLUP /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
./nb_scap_report.ksh $UP 20190601 20200301 PROCESS /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs


SCAP (Sustainable Clothing Action Plan) – Annual extract – March (will be relevant to TGR from March 2020)
select * from rms.period;

select count(1) from rms.SA_TRAN_HEAD;
select count(1) from rms.nb_hist_sa_tran_head;

select count(1) from rms.SA_TRAN_ITEM;
select count(1) from rms.nb_hist_sa_tran_ITEM;

select * from RMS.SA_STORE_DAY order by 2,3;
select * from RMS.nb_hist_SA_STORE_DAY order by 2,3;


--sa_tran_head
 133 296 641 -- ppd
  10 784 913 -- vpt
--nb_hist_sa_tran_head
 202 733 447 -- ppd
   7 691 072 -- vpt
--sa_tran_item
 357 924 771 -- ppd
  24 516 799 -- vpt
--nb_hist_sa_tran_item
 246 929 946 -- ppd
  18 443 130 -- vpt

 
cd /orabin/app/oracle/product/retail/batch/oracle/proc/src
sudo su - oracle
cat env.sh
cd /orabin/app/oracle/product/retail/batch/error
cd /orabin/app/oracle/product/retail/batch/log

select * from rms.code_detail where code_type='ELEM';
select * from rms.uda_values where uda_id='25';
 
select * from SA_TRAN_HEAD;
select * from SA_TRAN_ITEM;
select * from SA_STORE_DAY;
select * from SA_TRAN_HEAD;
select * from rms.nb_hist_sa_tran_head;
select * from rms.nb_hist_sa_tran_item;
select * from  MA_ASOS.nb_hist_sa_store_day;


MA_ASOS.MA_SCAP_REPORT_SQL.

PRE
RESA
RESA_ARCHIVED
ROLLUP
PROCESS

./nb_scap_report.ksh $UP 20190101 20191231 PRE /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
select * from MA_ASOS.ma_scap_report_filter;
./nb_scap_report.ksh $UP 20190101 20191231 RESA /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
select * from MA_ASOS.ma_scap_resa_extract;
./nb_scap_report.ksh $UP 20190101 20191231 RESA_ARCHIVED /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
./nb_scap_report.ksh $UP 20190101 20191231 ROLLUP /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
select * from MA_ASOS.ma_scap_resa_extract_rolled;
./nb_scap_report.ksh $UP 20190101 20191231 PROCESS /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs

select * from MA_ASOS.ma_scap_report_final; --227920 
select * from MA_ASOS.ma_scap_report;       --1264120


--  0:08:47  --01-JUN-20 to 07-JUN-20
select count(1) from MA_ASOS.ma_scap_report_final;        -- 59397
select count(1) from MA_ASOS.ma_scap_report;              -- 232133
select count(1) from MA_ASOS.ma_scap_resa_extract;        -- 153721
select count(1) from MA_ASOS.ma_scap_resa_extract_rolled; -- 147892

--    --  23-Nov-20 to 30-Nov-20
select count(1) from MA_ASOS.ma_scap_report_final;        -- 455695
select count(1) from MA_ASOS.ma_scap_report;              -- 3410320
select count(1) from MA_ASOS.ma_scap_resa_extract;        -- 6775424
select count(1) from MA_ASOS.ma_scap_resa_extract_rolled; -- 3611128

select * from MA_ASOS.ma_scap_resa_extract; --153721

 Processing started at: Apr 19 2021 13:38:01
Finished processing at: Apr 19 2021 13:44:02


New table  created in this epic which  will hold data for extract reporting are and these are not used by another program or batch

select * from MA_ASOS.ma_element_percent;
select * from MA_ASOS.ma_prod_type_element_percent;

insert into MA_ASOS.ma_prod_type_element_percent 
 select UDA_VALUE as product_typE,ELEMENT, ELEMENT_PERCENT from rms.uda_values, MA_ASOS.ma_element_percent where uda_id='25';
 
select * from MA_ASOS.ma_item_fabric_comp;



 select max_concurrent_threads
     from rms_plsql_batch_config
    where program_name = 'NB_SCAP_REPORT';


select * from all_tables where table_name like 'NB_HIST%';

select count(1) from rms.nb_hist_sa_tran_head; --





NOT MA_ASOS.MA_SCAP_REPORT_SQL


MA_ASOS.MA_SCAP_REPORT_SQL.


01-SEP-19

select sd.BUSINESS_DATE,st.store,st.STORE_DAY_SEQ_NO,st.TRAN_TYPE, count(1) from RMS.SA_TRAN_HEAD st, SA_STORE_DAY sd where 
    st.STORE_DAY_SEQ_NO = sd.STORE_DAY_SEQ_NO and sd.BUSINESS_DATE <= ('01-SEP-19')
    group by sd.BUSINESS_DATE,st.store,st.STORE_DAY_SEQ_NO,st.TRAN_TYPE order by 1,2;

select sd.BUSINESS_DATE,count(1) from RMS.SA_TRAN_HEAD st, SA_STORE_DAY sd where 
    st.STORE_DAY_SEQ_NO = sd.STORE_DAY_SEQ_NO and sd.BUSINESS_DATE <= ('01-SEP-19')
    group by sd.BUSINESS_DATE;
    
select sd.BUSINESS_DATE,count(1) from RMS.SA_TRAN_HEAD st, SA_STORE_DAY sd where 
    st.STORE_DAY_SEQ_NO = sd.STORE_DAY_SEQ_NO --and sd.BUSINESS_DATE >= ('01-SEP-19')
    group by sd.BUSINESS_DATE;
    
    
    
dELEte ma_asos.MA_ELEMENT_PERCENT;
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('54','1');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('55','2');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('56','3');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('198','4');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('57','5');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('58','6');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('199','7');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('59','8');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('108','9');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('60','10');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('200','11');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('201','12');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('88','13');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('202','14');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('203','15');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('204','16');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('205','17');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('61','18');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('82','19');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('62','20');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('63','21');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('64','22');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('86','23');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('79','24');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('78','25');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('65','26');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('66','27');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('67','28');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('68','29');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('69','30');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('111','31');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('206','32');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('207','33');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('70','34');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('71','35');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('133','36');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('134','37');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('1','38');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('2','39');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('135','40');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('72','41');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('129','42');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('112','43');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('3','44');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('136','45');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('4','46');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('5','47');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('137','48');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('6','49');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('120','50');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('138','51');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('139','52');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('91','53');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('95','54');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('96','55');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('140','56');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('7','57');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('116','58');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('103','59');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('141','60');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('142','61');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('143','62');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('144','63');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('121','64');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('8','65');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('145','66');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('9','67');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('87','68');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('146','69');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('10','70');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('11','71');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('12','72');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('13','73');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('14','74');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('113','75');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('15','76');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('16','77');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('147','78');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('17','79');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('18','80');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('148','81');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('90','82');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('101','83');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('102','84');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('93','85');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('19','86');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('20','87');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('149','88');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('21','89');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('22','90');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('23','91');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('132','92');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('24','93');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('130','94');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('131','95');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('83','96');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('25','97');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('150','98');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('151','99');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('152','100');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('153','101');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('26','102');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('154','103');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('27','104');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('84','105');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('28','106');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('29','107');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('30','108');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('94','109');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('155','110');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('156','111');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('157','112');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('158','113');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('159','114');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('160','115');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('161','116');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('114','117');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('31','118');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('32','119');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('162','120');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('107','121');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('33','122');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('123','123');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('124','124');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('125','125');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('126','126');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('127','127');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('128','128');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('77','129');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('75','130');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('115','131');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('105','132');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('34','133');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('35','134');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('163','135');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('85','136');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('36','137');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('37','138');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('38','139');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('39','140');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('40','141');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('41','142');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('117','143');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('118','144');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('164','145');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('42','146');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('165','147');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('119','148');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('166','149');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('43','150');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('44','151');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('46','152');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('167','153');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('168','154');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('92','155');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('76','156');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('99','157');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('100','158');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('169','159');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('45','160');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('170','161');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('171','162');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('172','163');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('173','164');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('74','165');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('194','166');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('47','167');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('48','168');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('174','169');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('175','170');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('176','171');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('177','172');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('178','173');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('179','174');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('180','175');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('181','176');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('182','177');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('183','178');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('184','179');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('185','180');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('186','181');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('187','182');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('188','183');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('189','184');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('190','185');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('191','186');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('122','187');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('81','188');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('80','189');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('73','190');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('49','191');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('104','192');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('106','193');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('192','194');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('193','195');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('195','196');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('50','197');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('51','198');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('89','199');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('98','200');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('97','201');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('196','202');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('52','203');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('109','204');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('110','205');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('197','206');
INSERT INTO ma_asos.MA_ELEMENT_PERCENT (ELEMENT, ELEMENT_PERCENT) VALUES ('53','207');






[oracle@vptpreuwormsd01.kingsway.asos.com][VPTMOM1]/orabin/app/oracle/product/retail/batch/oracle/proc/bin $./nb_scap_report.ksh $UP 20190601 20200301 PRE /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
Running nb_scap_report Batch
LOGPATH= /home/siddeshk/logs
ERRPATH= /home/siddeshk/logs
EXPORTPATH= /home/siddeshk/logs
LOGFILE= /home/siddeshk/logs/nb_scap_report.ksh_20210420100848.log
ERRFILE= /home/siddeshk/logs/err_nb_scap_report.ksh_20210420100848.log
/orabin/app/oracle/product/12.1.0/dbhome_1

[oracle@vptpreuwormsd01.kingsway.asos.com][VPTMOM1]/orabin/app/oracle/product/retail/batch/oracle/proc/bin $./nb_scap_report.ksh $UP 20190601 20200301 RESA /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
Running nb_scap_report Batch
LOGPATH= /home/siddeshk/logs
ERRPATH= /home/siddeshk/logs
EXPORTPATH= /home/siddeshk/logs
LOGFILE= /home/siddeshk/logs/nb_scap_report.ksh_20210420100928.log
ERRFILE= /home/siddeshk/logs/err_nb_scap_report.ksh_20210420100928.log
/orabin/app/oracle/product/12.1.0/dbhome_1
You have new mail in /var/spool/mail/oracle
[oracle@vptpreuwormsd01.kingsway.asos.com][VPTMOM1]/orabin/app/oracle/product/retail/batch/oracle/proc/bin $./nb_scap_report.ksh $UP 20190601 20200301 RESA_ARCHIVED /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
Running nb_scap_report Batch
LOGPATH= /home/siddeshk/logs
ERRPATH= /home/siddeshk/logs
EXPORTPATH= /home/siddeshk/logs
LOGFILE= /home/siddeshk/logs/nb_scap_report.ksh_20210420101032.log
ERRFILE= /home/siddeshk/logs/err_nb_scap_report.ksh_20210420101032.log
/orabin/app/oracle/product/12.1.0/dbhome_1
[oracle@vptpreuwormsd01.kingsway.asos.com][VPTMOM1]/orabin/app/oracle/product/retail/batch/oracle/proc/bin $./nb_scap_report.ksh $UP 20190601 20200301 ROLLUP /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
Running nb_scap_report Batch
LOGPATH= /home/siddeshk/logs
ERRPATH= /home/siddeshk/logs
EXPORTPATH= /home/siddeshk/logs
LOGFILE= /home/siddeshk/logs/nb_scap_report.ksh_20210420101056.log
ERRFILE= /home/siddeshk/logs/err_nb_scap_report.ksh_20210420101056.log
/orabin/app/oracle/product/12.1.0/dbhome_1
[oracle@vptpreuwormsd01.kingsway.asos.com][VPTMOM1]/orabin/app/oracle/product/retail/batch/oracle/proc/bin $./nb_scap_report.ksh $UP 20190601 20200301 PROCESS /home/siddeshk/logs /home/siddeshk/logs /home/siddeshk/logs
Running nb_scap_report Batch
LOGPATH= /home/siddeshk/logs
ERRPATH= /home/siddeshk/logs
EXPORTPATH= /home/siddeshk/logs
LOGFILE= /home/siddeshk/logs/nb_scap_report.ksh_20210420101100.log
ERRFILE= /home/siddeshk/logs/err_nb_scap_report.ksh_20210420101100.log
/orabin/app/oracle/product/12.1.0/dbhome_1
