
Begin

insert into tran_data_A (ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TIMESTAMP, REF_PACK_NO,TOTAL_COST_EXCL_ELC)
select ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, '11-NOV-21' TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TRAN_DATA_TIMESTAMP, REF_PACK_NO, null as TOTAL_COST_EXCL_ELC
from if_tran_data_bk_reten where rownum <='5000000';

insert into tran_data_A (ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TIMESTAMP, REF_PACK_NO,TOTAL_COST_EXCL_ELC)
select ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, '12-NOV-21' TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TRAN_DATA_TIMESTAMP, REF_PACK_NO, null as TOTAL_COST_EXCL_ELC
from if_tran_data_bk_reten where rownum <='5000000';

insert into tran_data_a (ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TIMESTAMP, REF_PACK_NO,TOTAL_COST_EXCL_ELC)
select ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, '13-NOV-21' TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TRAN_DATA_TIMESTAMP, REF_PACK_NO, null as TOTAL_COST_EXCL_ELC
from if_tran_data_bk_reten where rownum <='5000000';

insert into tran_data_A (ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TIMESTAMP, REF_PACK_NO,TOTAL_COST_EXCL_ELC)
select ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, '14-NOV-21' TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TRAN_DATA_TIMESTAMP, REF_PACK_NO, null as TOTAL_COST_EXCL_ELC
from if_tran_data_bk_reten where rownum <='5000000';

commit;
end;
/

select * from rms.daily_data where data_date ='08-MAY-21';
select * from NB_STG_FIF_GL_DATA where ACCOUNTING_DATE ='08-MAY-21';
delete from NB_STG_FIF_GL_DATA where ACCOUNTING_DATE ='08-MAY-21';

select * from nb_KEY_MAP_GL where PROCESSED_DATE ='08-MAY-21';
select * from KEY_MAP_GL where PROCESSED_DATE ='08-MAY-21';

create table if_tran_data_bk_reten as
select * from rms.if_tran_data;

select count(1) from if_tran_data; --12193093
select count(1) from tran_data_b;
select TRAN_DATE,count(1) from tran_data_a group by TRAN_DATE;
select TRAN_DATE,count(1) from tran_data_b group by TRAN_DATE;

select TRAN_DATE,count(1) from tran_data group by TRAN_DATE;

select * from period;

update tran_data_b set TRAN_DATE = '08-MAY-21' where trunc(TRAN_DATE) = '09-MAY-21';
update tran_data_a set TRAN_DATE = '08-MAY-21' where trunc(TRAN_DATE) = '09-MAY-21';
 
insert into tran_data_b (ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TIMESTAMP, REF_PACK_NO,TOTAL_COST_EXCL_ELC)

select ITEM, DEPT, CLASS, SUBCLASS, PACK_IND, LOC_TYPE, LOCATION, TRAN_DATE, TRAN_CODE, ADJ_CODE, UNITS, TOTAL_COST, TOTAL_RETAIL, REF_NO_1, 
REF_NO_2, GL_REF_NO, OLD_UNIT_RETAIL, NEW_UNIT_RETAIL, PGM_NAME, SALES_TYPE, VAT_RATE, AV_COST, TRAN_DATA_TIMESTAMP, REF_PACK_NO, null as TOTAL_COST_EXCL_ELC
from if_tran_data_bk_reten ;

select tran_code,count(1) from if_tran_data group by tran_code; 


select * from if_tran_data where item = '10581760';

delete from tran_data_B where dept ='9999';
select * from half_data where dept ='9999';
select * from half_data_budget where dept ='9999';
select * from month_data_budget where dept ='9999';
select * from rms.daily_data where dept ='9999';
select * from rms.week_data where dept ='9999';
select * from rms.month_data where dept ='9999';

select DATA_DATE,count(1) from rms.daily_data group by DATA_DATE order by 1 desc;
select EOW_DATE,count(1) from rms.week_data group by EOW_DATE order by 1 desc;
select EOM_DATE,count(1) from rms.month_data group by EOM_DATE order by 1 desc;


select * from half_data where location in (20011,20000,20010,20012);
select * from half_data_budget where location in (20011,20000,20010,20012);
select * from month_data_budget where location in (20011,20000,20010,20012);
select * from rms.daily_data where location in (20011,20000,20010,20012);
select * from rms.week_data where location in (20011,20000,20010,20012);
select * from rms.month_data where location in (20011,20000,20010,20012);

drop table half_data_bk;

select * from rms.daily_data where data_date ='08-MAY-21';
select * from rms.daily_data where data_date ='08-MAY-21';
select * from rms.week_data where EOW_DATE ='08-MAY-21';
select * from rms.month_data where EOM_DATE ='30-SEP-18';



-- daily_data

set serveroutput on;
set timing on;

declare
c_commit number(10):= '0';
l_DATA_DATE                rms.daily_data.DATA_DATE%type;
l_EOW_DATE                rms.daily_data.EOW_DATE%type;

cursor c_template is    
    select today as DATA_DATE,
        next_day(today,'SUN') as EOW_DATE 
    from (select date '2018-06-11'+level today from dual connect by level<=110);     

begin
for i in c_template loop
		l_EOW_DATE                    :=i.EOW_DATE;
        l_DATA_DATE                    :=i.DATA_DATE;

 insert into rms.daily_data 
     select DEPT, CLASS, SUBCLASS, LOC_TYPE, LOCATION, l_DATA_DATE, CURRENCY_IND, SET_OF_BOOKS_ID, HALF_NO, MONTH_NO, l_EOW_DATE, WEEK_NO, DAY_NO, STOCK_ADJ_RETAIL, STOCK_ADJ_COST, STOCK_ADJ_COGS_RETAIL, STOCK_ADJ_COGS_COST, PURCH_RETAIL, PURCH_COST, RTV_RETAIL, RTV_COST, FREIGHT_COST, UP_CHRG_AMT_PROFIT, UP_CHRG_AMT_EXP, TSF_IN_RETAIL, TSF_IN_COST, TSF_IN_BOOK_RETAIL, TSF_IN_BOOK_COST, TSF_OUT_RETAIL, TSF_OUT_COST, TSF_OUT_BOOK_RETAIL, TSF_OUT_BOOK_COST, NET_SALES_RETAIL, NET_SALES_COST, NET_SALES_RETAIL_EX_VAT, RETURNS_RETAIL, RETURNS_COST, PROM_MARKDOWN_RETAIL, MARKDOWN_CAN_RETAIL, EMPL_DISC_RETAIL, WORKROOM_AMT, CASH_DISC_AMT, SALES_UNITS, MARKUP_RETAIL, MARKUP_CAN_RETAIL, CLEAR_MARKDOWN_RETAIL, PERM_MARKDOWN_RETAIL, COST_VARIANCE_AMT, RECLASS_IN_COST, RECLASS_IN_RETAIL, RECLASS_OUT_COST, RECLASS_OUT_RETAIL, FREIGHT_CLAIM_RETAIL, FREIGHT_CLAIM_COST, INTERCOMPANY_IN_RETAIL, INTERCOMPANY_IN_COST, INTERCOMPANY_OUT_RETAIL, INTERCOMPANY_OUT_COST, INTERCOMPANY_MARKUP, INTERCOMPANY_MARKDOWN, WO_ACTIVITY_UPD_INV, WO_ACTIVITY_POST_FIN, DEAL_INCOME_SALES, DEAL_INCOME_PURCH, RESTOCKING_FEE, RETAIL_COST_VARIANCE, MARGIN_COST_VARIANCE, FRANCHISE_SALES_RETAIL, FRANCHISE_SALES_COST, FRANCHISE_RETURNS_RETAIL, FRANCHISE_RETURNS_COST, FRANCHISE_MARKUP_RETAIL, FRANCHISE_MARKDOWN_RETAIL, FRANCHISE_RESTOCKING_FEE, VAT_IN, VAT_OUT, WEIGHT_VARIANCE_RETAIL, RECOVERABLE_TAX, NET_SALES_NON_INV_RETAIL, NET_SALES_NON_INV_RTL_EX_VAT, NET_SALES_NON_INV_COST, REC_COST_ADJ_VARIANCE
    from daily_data where data_date ='01-OCT-18';
 
end loop;
commit;

exception	
when others then
    dbms_output.put_line('Exception blcok'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
end;
/


select * from rms.week_data where EOW_DATE ='07-OCT-18';
-- Week data

create table sl_eow as
  select today as DATA_DATE,
        next_day(today,'SUN') as EOW_DATE 
    from (select date '2018-06-11'+level today from dual connect by level<=174);  

select distinct EOW_DATE from sl_eow;

select DEPT, CLASS, SUBCLASS, LOC_TYPE, LOCATION, HALF_NO, MONTH_NO, WEEK_NO, CURRENCY_IND, EOW_DATE, SET_OF_BOOKS_ID, OPN_STK_RETAIL, OPN_STK_COST, STOCK_ADJ_RETAIL, STOCK_ADJ_COST, STOCK_ADJ_COGS_RETAIL, STOCK_ADJ_COGS_COST, PURCH_RETAIL, PURCH_COST, RTV_RETAIL, RTV_COST, FREIGHT_COST, UP_CHRG_AMT_PROFIT, UP_CHRG_AMT_EXP, TSF_IN_RETAIL, TSF_IN_COST, TSF_IN_BOOK_RETAIL, TSF_IN_BOOK_COST, TSF_OUT_RETAIL, TSF_OUT_COST, TSF_OUT_BOOK_RETAIL, TSF_OUT_BOOK_COST, NET_SALES_RETAIL, NET_SALES_RETAIL_EX_VAT, NET_SALES_COST, RETURNS_RETAIL, RETURNS_COST, MARKUP_RETAIL, MARKUP_CAN_RETAIL, CLEAR_MARKDOWN_RETAIL, PERM_MARKDOWN_RETAIL, PROM_MARKDOWN_RETAIL, MARKDOWN_CAN_RETAIL, SHRINKAGE_RETAIL, SHRINKAGE_COST, EMPL_DISC_RETAIL, WORKROOM_AMT, CASH_DISC_AMT, CLS_STK_RETAIL, CLS_STK_COST, CUM_MARKON_PCT, GROSS_MARGIN_AMT, SALES_UNITS, COST_VARIANCE_AMT, HTD_GAFS_RETAIL, HTD_GAFS_COST, STOCKTAKE_ADJ_RETAIL, STOCKTAKE_ADJ_COST, RECLASS_IN_COST, RECLASS_IN_RETAIL, RECLASS_OUT_COST, RECLASS_OUT_RETAIL, FREIGHT_CLAIM_RETAIL, FREIGHT_CLAIM_COST, INTERCOMPANY_IN_RETAIL, INTERCOMPANY_IN_COST, INTERCOMPANY_OUT_RETAIL, INTERCOMPANY_OUT_COST, INTERCOMPANY_MARKUP, INTERCOMPANY_MARKDOWN, WO_ACTIVITY_UPD_INV, WO_ACTIVITY_POST_FIN, INTERCOMPANY_MARGIN, DEAL_INCOME_SALES, DEAL_INCOME_PURCH, RESTOCKING_FEE, RETAIL_COST_VARIANCE, MARGIN_COST_VARIANCE, FRANCHISE_SALES_RETAIL, FRANCHISE_SALES_COST, FRANCHISE_RETURNS_RETAIL, FRANCHISE_RETURNS_COST, FRANCHISE_MARKUP_RETAIL, FRANCHISE_MARKDOWN_RETAIL, FRANCHISE_RESTOCKING_FEE, VAT_IN, VAT_OUT, WEIGHT_VARIANCE_RETAIL, RECOVERABLE_TAX, NET_SALES_NON_INV_RETAIL, NET_SALES_NON_INV_RTL_EX_VAT, NET_SALES_NON_INV_COST, REC_COST_ADJ_VARIANCE
    from rms.week_data where EOW_DATE ='07-OCT-18';


set serveroutput on;
set timing on;

declare
c_commit number(10):= '0';
l_DATA_DATE                rms.daily_data.DATA_DATE%type;
l_EOW_DATE                rms.daily_data.EOW_DATE%type;

cursor c_template is    
   select distinct EOW_DATE from sl_eow order by 1;   

begin
for i in c_template loop
		l_EOW_DATE                    :=i.EOW_DATE;

 insert into rms.week_data 
 select DEPT, CLASS, SUBCLASS, LOC_TYPE, LOCATION, HALF_NO, MONTH_NO, WEEK_NO, CURRENCY_IND, l_EOW_DATE, SET_OF_BOOKS_ID, OPN_STK_RETAIL, OPN_STK_COST, STOCK_ADJ_RETAIL, STOCK_ADJ_COST, STOCK_ADJ_COGS_RETAIL, STOCK_ADJ_COGS_COST, PURCH_RETAIL, PURCH_COST, RTV_RETAIL, RTV_COST, FREIGHT_COST, UP_CHRG_AMT_PROFIT, UP_CHRG_AMT_EXP, TSF_IN_RETAIL, TSF_IN_COST, TSF_IN_BOOK_RETAIL, TSF_IN_BOOK_COST, TSF_OUT_RETAIL, TSF_OUT_COST, TSF_OUT_BOOK_RETAIL, TSF_OUT_BOOK_COST, NET_SALES_RETAIL, NET_SALES_RETAIL_EX_VAT, NET_SALES_COST, RETURNS_RETAIL, RETURNS_COST, MARKUP_RETAIL, MARKUP_CAN_RETAIL, CLEAR_MARKDOWN_RETAIL, PERM_MARKDOWN_RETAIL, PROM_MARKDOWN_RETAIL, MARKDOWN_CAN_RETAIL, SHRINKAGE_RETAIL, SHRINKAGE_COST, EMPL_DISC_RETAIL, WORKROOM_AMT, CASH_DISC_AMT, CLS_STK_RETAIL, CLS_STK_COST, CUM_MARKON_PCT, GROSS_MARGIN_AMT, SALES_UNITS, COST_VARIANCE_AMT, HTD_GAFS_RETAIL, HTD_GAFS_COST, STOCKTAKE_ADJ_RETAIL, STOCKTAKE_ADJ_COST, RECLASS_IN_COST, RECLASS_IN_RETAIL, RECLASS_OUT_COST, RECLASS_OUT_RETAIL, FREIGHT_CLAIM_RETAIL, FREIGHT_CLAIM_COST, INTERCOMPANY_IN_RETAIL, INTERCOMPANY_IN_COST, INTERCOMPANY_OUT_RETAIL, INTERCOMPANY_OUT_COST, INTERCOMPANY_MARKUP, INTERCOMPANY_MARKDOWN, WO_ACTIVITY_UPD_INV, WO_ACTIVITY_POST_FIN, INTERCOMPANY_MARGIN, DEAL_INCOME_SALES, DEAL_INCOME_PURCH, RESTOCKING_FEE, RETAIL_COST_VARIANCE, MARGIN_COST_VARIANCE, FRANCHISE_SALES_RETAIL, FRANCHISE_SALES_COST, FRANCHISE_RETURNS_RETAIL, FRANCHISE_RETURNS_COST, FRANCHISE_MARKUP_RETAIL, FRANCHISE_MARKDOWN_RETAIL, FRANCHISE_RESTOCKING_FEE, VAT_IN, VAT_OUT, WEIGHT_VARIANCE_RETAIL, RECOVERABLE_TAX, NET_SALES_NON_INV_RETAIL, NET_SALES_NON_INV_RTL_EX_VAT, NET_SALES_NON_INV_COST, REC_COST_ADJ_VARIANCE
    from rms.week_data where EOW_DATE ='07-OCT-18';

end loop;

exception	
when others then
    dbms_output.put_line('Exception blcok'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
end;
/


-- MOnth_data

select distinct EOW_DATE from sl_eow where eow_date in ('30-SEP-18','02-SEP-18','05-AUG-18','08-JUL-18');
select * from rms.month_data where EOM_DATE ='30-SEP-18';
select DEPT, CLASS, SUBCLASS, LOC_TYPE, LOCATION, HALF_NO, MONTH_NO, CURRENCY_IND, EOM_DATE, SET_OF_BOOKS_ID, OPN_STK_RETAIL, OPN_STK_COST, STOCK_ADJ_RETAIL, STOCK_ADJ_COST, STOCK_ADJ_COGS_RETAIL, STOCK_ADJ_COGS_COST, PURCH_RETAIL, PURCH_COST, RTV_RETAIL, RTV_COST, FREIGHT_COST, UP_CHRG_AMT_PROFIT, UP_CHRG_AMT_EXP, TSF_IN_RETAIL, TSF_IN_COST, TSF_IN_BOOK_RETAIL, TSF_IN_BOOK_COST, TSF_OUT_RETAIL, TSF_OUT_COST, TSF_OUT_BOOK_RETAIL, TSF_OUT_BOOK_COST, NET_SALES_RETAIL, NET_SALES_RETAIL_EX_VAT, NET_SALES_COST, RETURNS_RETAIL, RETURNS_COST, MARKUP_RETAIL, MARKUP_CAN_RETAIL, CLEAR_MARKDOWN_RETAIL, PERM_MARKDOWN_RETAIL, PROM_MARKDOWN_RETAIL, MARKDOWN_CAN_RETAIL, SHRINKAGE_COST, SHRINKAGE_RETAIL, EMPL_DISC_RETAIL, WORKROOM_AMT, CASH_DISC_AMT, CLS_STK_RETAIL, CLS_STK_COST, CUM_MARKON_PCT, GROSS_MARGIN_AMT, SALES_UNITS, COST_VARIANCE_AMT, HTD_GAFS_RETAIL, HTD_GAFS_COST, INTER_STOCKTAKE_SALES_AMT, INTER_STOCKTAKE_SHRINK_AMT, STOCKTAKE_MTD_SALES_AMT, STOCKTAKE_MTD_SHRINK_AMT, STOCKTAKE_BOOKSTK_RETAIL, STOCKTAKE_BOOKSTK_COST, STOCKTAKE_ACTSTK_RETAIL, STOCKTAKE_ACTSTK_COST, RECLASS_IN_COST, RECLASS_IN_RETAIL, RECLASS_OUT_COST, RECLASS_OUT_RETAIL, FREIGHT_CLAIM_RETAIL, FREIGHT_CLAIM_COST, INTERCOMPANY_IN_RETAIL, INTERCOMPANY_IN_COST, INTERCOMPANY_OUT_RETAIL, INTERCOMPANY_OUT_COST, INTERCOMPANY_MARKUP, INTERCOMPANY_MARKDOWN, WO_ACTIVITY_UPD_INV, WO_ACTIVITY_POST_FIN, INTERCOMPANY_MARGIN, DEAL_INCOME_SALES, DEAL_INCOME_PURCH, RESTOCKING_FEE, RETAIL_COST_VARIANCE, MARGIN_COST_VARIANCE, FRANCHISE_SALES_RETAIL, FRANCHISE_SALES_COST, FRANCHISE_RETURNS_RETAIL, FRANCHISE_RETURNS_COST, FRANCHISE_MARKUP_RETAIL, FRANCHISE_MARKDOWN_RETAIL, FRANCHISE_RESTOCKING_FEE, VAT_IN, VAT_OUT, WEIGHT_VARIANCE_RETAIL, RECOVERABLE_TAX, NET_SALES_NON_INV_RETAIL, NET_SALES_NON_INV_RTL_EX_VAT, NET_SALES_NON_INV_COST, REC_COST_ADJ_VARIANCE
    from rms.month_data where EOM_DATE ='30-SEP-18';
    
    
    
declare
c_commit number(10):= '0';
l_DATA_DATE                rms.daily_data.DATA_DATE%type;
l_EOW_DATE                rms.daily_data.EOW_DATE%type;

cursor c_template is    
select distinct EOW_DATE from sl_eow where eow_date in ('02-SEP-18','05-AUG-18','08-JUL-18');

begin
for i in c_template loop
		l_EOW_DATE                    :=i.EOW_DATE;

 insert into rms.month_data 
select DEPT, CLASS, SUBCLASS, LOC_TYPE, LOCATION, HALF_NO, MONTH_NO, CURRENCY_IND, l_EOW_DATE, SET_OF_BOOKS_ID, OPN_STK_RETAIL, OPN_STK_COST, STOCK_ADJ_RETAIL, STOCK_ADJ_COST, STOCK_ADJ_COGS_RETAIL, STOCK_ADJ_COGS_COST, PURCH_RETAIL, PURCH_COST, RTV_RETAIL, RTV_COST, FREIGHT_COST, UP_CHRG_AMT_PROFIT, UP_CHRG_AMT_EXP, TSF_IN_RETAIL, TSF_IN_COST, TSF_IN_BOOK_RETAIL, TSF_IN_BOOK_COST, TSF_OUT_RETAIL, TSF_OUT_COST, TSF_OUT_BOOK_RETAIL, TSF_OUT_BOOK_COST, NET_SALES_RETAIL, NET_SALES_RETAIL_EX_VAT, NET_SALES_COST, RETURNS_RETAIL, RETURNS_COST, MARKUP_RETAIL, MARKUP_CAN_RETAIL, CLEAR_MARKDOWN_RETAIL, PERM_MARKDOWN_RETAIL, PROM_MARKDOWN_RETAIL, MARKDOWN_CAN_RETAIL, SHRINKAGE_COST, SHRINKAGE_RETAIL, EMPL_DISC_RETAIL, WORKROOM_AMT, CASH_DISC_AMT, CLS_STK_RETAIL, CLS_STK_COST, CUM_MARKON_PCT, GROSS_MARGIN_AMT, SALES_UNITS, COST_VARIANCE_AMT, HTD_GAFS_RETAIL, HTD_GAFS_COST, INTER_STOCKTAKE_SALES_AMT, INTER_STOCKTAKE_SHRINK_AMT, STOCKTAKE_MTD_SALES_AMT, STOCKTAKE_MTD_SHRINK_AMT, STOCKTAKE_BOOKSTK_RETAIL, STOCKTAKE_BOOKSTK_COST, STOCKTAKE_ACTSTK_RETAIL, STOCKTAKE_ACTSTK_COST, RECLASS_IN_COST, RECLASS_IN_RETAIL, RECLASS_OUT_COST, RECLASS_OUT_RETAIL, FREIGHT_CLAIM_RETAIL, FREIGHT_CLAIM_COST, INTERCOMPANY_IN_RETAIL, INTERCOMPANY_IN_COST, INTERCOMPANY_OUT_RETAIL, INTERCOMPANY_OUT_COST, INTERCOMPANY_MARKUP, INTERCOMPANY_MARKDOWN, WO_ACTIVITY_UPD_INV, WO_ACTIVITY_POST_FIN, INTERCOMPANY_MARGIN, DEAL_INCOME_SALES, DEAL_INCOME_PURCH, RESTOCKING_FEE, RETAIL_COST_VARIANCE, MARGIN_COST_VARIANCE, FRANCHISE_SALES_RETAIL, FRANCHISE_SALES_COST, FRANCHISE_RETURNS_RETAIL, FRANCHISE_RETURNS_COST, FRANCHISE_MARKUP_RETAIL, FRANCHISE_MARKDOWN_RETAIL, FRANCHISE_RESTOCKING_FEE, VAT_IN, VAT_OUT, WEIGHT_VARIANCE_RETAIL, RECOVERABLE_TAX, NET_SALES_NON_INV_RETAIL, NET_SALES_NON_INV_RTL_EX_VAT, NET_SALES_NON_INV_COST, REC_COST_ADJ_VARIANCE
    from rms.month_data where EOM_DATE ='30-SEP-18';

end loop;

exception	
when others then
    dbms_output.put_line('Exception blcok'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
end;
/




















----------------------------------------------------------------------------------------------------------------


set SERVEROUTPUT ON;
set timing ON;
  DECLARE

l_dd         NUMBER;
l_mm         NUMBER;
l_yyyy       NUMBER;
out_dd_454    NUMBER;
out_wk_454    NUMBER;
out_mm_454    NUMBER;
out_yyyy_454  NUMBER;
return_code   VARCHAR2(255);
error_message VARCHAR2(255);
    

      BEGIN
      
  select TO_NUMBER(TO_CHAR(vdate -10,'DD')) into L_dd  from period;
  select TO_NUMBER(TO_CHAR(vdate -10,'MM')) into L_mm from period;
  select TO_NUMBER(TO_CHAR(vdate -10,'YYYY')) into L_yyyy from period;
  
  
   rms.CAL_TO_454                      (L_dd         ,
                                        L_mm         ,
                                        L_yyyy       ,
                                        out_dd_454    ,
                                        out_wk_454    ,
                                        out_mm_454    ,
                                        out_yyyy_454  ,
                                        return_code   ,
                                        error_message );
                                        
                                dbms_output.put_line('half_no '|| '20191');                 
                                 dbms_output.put_line('out_dd_454 '|| out_dd_454);
                                 dbms_output.put_line('out_wk_454 '|| out_mm_454);
                                 dbms_output.put_line('out_mm_454 '|| out_mm_454);
                                 dbms_output.put_line('out_yyyy_454 '|| out_yyyy_454);
                                 dbms_output.put_line('error_message '|| error_message);
                                 dbms_output.put_line('return_code '|| return_code);                                


EXCEPTION
 
   when OTHERS THEN
      dbms_output.put_line('Exception blcok'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
 
END;




select vdate from period;
select * from half_data;
select * from half_data_budget where location ='20010';
delete from month_data where location ='20012';
delete from week_data where location ='20012';

select * from store where store not in (select distinct location from half_data_budget);
select * from wh where wh not in (select distinct location from half_data_budget);



set serveroutput on;
set timing on;
declare

 cursor C_SUBCLASS is
    select store,STORE_TYPE,CURRENCY_CODE from store where store not in (select distinct location from half_data_budget);

 L_counter NUMBER(10);
 L_error_message VARCHAR2(255);

begin

 for i_rec in C_SUBCLASS LOOP

    if STKLEDGR_INSERTS_SQL.ADD_LOC (i_rec.store_type,
                                      i_rec.store,
                                       i_rec.CURRENCY_CODE,
                                       L_counter,
                                       L_error_message) = FALSE then
      dbms_output.put_line( i_rec.store);
      dbms_output.put_line( i_rec.store|| L_error_message );
      dbms_output.put_line( L_counter);
    end if;

 end loop;

exception
  when others then
     dbms_output.put_line( SQLERRM );

end;
/
