select * from all_tables where table_name like '%RECEI%';

select * from RIBAQ.ETRECEIVINGTABLE;

select count(1) from RIBAQ.ETINVADJUSTTABLE;
select count(1) from RIBAQ.ETITEMLOCFROMRMSTABLE;
select count(1) from RIBAQ.ETALLOCFROMRMSTABLE;

select * from RIBAQ.ETINVADJUSTTABLE;
select * from RIBAQ.AQ$_ETINVADJUSTTABLE_S;


select * from ALL_DB_LINKS;
3262	fk4zpkkq03dnx


select * from RIBAQ.ETITEMSFROMRMSTABLE;

select * from RIBAQ.ETALLOCFROMRMSTABLE;
select * from RIBAQ.AQ$_ETXALLOCTABLE_S;




RIBAQ	AQ$_ETALLOCFROMRMSTABLE_S	RETAIL_DATA
RIBAQ	AQ$_ETXALLOCTABLE_S	RETAIL_DATA


SYS.AQ$_JMS_MESSAGE(SYS.AQ$_JMS_HEADER(SYS.AQ$_AGENT(' ', NULL, 0), NULL, 'MULESOFT', NULL, NULL, NULL, 
SYS.AQ$_JMS_USERPROPARRAY(SYS.AQ$_JMS_USERPROPERTY('JMS_OracleConnectionID', 100, '81b246fc327ff01ce0532a65620a37c8', NULL, 27),
SYS.AQ$_JMS_USERPROPERTY('JMS_OracleDeliveryMode', 100, '2', NULL, 27), SYS.AQ$_JMS_USERPROPERTY('threadValue', 100, '1', NULL, 27), 
SYS.AQ$_JMS_USERPROPERTY('JMS_OracleTimestamp', 200, NULL, 1549973285789, 24))), NULL, 0, 2099, NULL, NULL, NULL, 'oracle.sql.CLOB@92be95a', NULL)


