select week_num,count(1) from rms.REPL_ATTR_UPD_HIST group by week_num order by 1

201801	78241
201802	78241
201803	78241
201804	78241
201805	78241

RPLATHISTPRG - DB partitions

  SELECT  to_char(vdate,'WW'),
               to_char(vdate,'YYYY'),
               repl_attr_hist_retention_weeks 
         FROM  rms.period,
               rms.system_options; --49	2018	52
               
               select 44-52 from dual;
select * from rms.REPL_ATTR_UPD_HIST;



select distinct ACTIVATE_DATE, DEACTIVATE_DATE from rms.REPL_ATTR_UPD_HIST where week_num is null;

select * from all_Sequences where sequence_name like '%REPL_ATTR%';
SELECT distinct TABLE_NAME FROM all_tab_partitions and owner in ('RMS','MA_ASOS');

SELECT * FROM all_tab_partitions
    WHERE table_name like '%REPL_ATTR%';
    
SELECT * FROM all_tab_partitions
    WHERE table_name like '%REPL_RESULTS%';
     AND table_owner = :ps_table_owner
     AND SUBSTR(partition_name,21) <= :ls_trunc_part;

select week_num,count(1) from rms.REPL_ATTR_UPD_HIST group by week_num order by 1;
         
 insert into rms.REPL_ATTR_UPD_HIST 
select rms.REPL_ATTR_UPD_ID_SEQ.nextval, DEPT, CLASS, SUBCLASS, DIFF_AGGREGATE, ITEM, LOC_TYPE, LOCATION, ITEM_PARENT, ITEM_GRANDPARENT, SIZE_PROFILE_IND, 
PRIMARY_REPL_SUPPLIER, ORIGIN_COUNTRY_ID, REVIEW_CYCLE, STOCK_CAT, REPL_ORDER_CTRL, SOURCE_WH, ACTIVATE_DATE, DEACTIVATE_DATE, PRES_STOCK, 
DEMO_STOCK, REPL_METHOD, MIN_STOCK, MAX_STOCK, INCR_PCT, MIN_SUPPLY_DAYS, MAX_SUPPLY_DAYS, TIME_SUPPLY_HORIZON, INV_SELLING_DAYS, SERVICE_LEVEL,
LOST_SALES_FACTOR, REJECT_STORE_ORD_IND, NON_SCALING_IND, MAX_SCALE_VALUE, PICKUP_LEAD_TIME, WH_LEAD_TIME, TERMINAL_STOCK_QTY, SEASON_ID, PHASE_ID, 
PRIMARY_PACK_NO, PRIMARY_PACK_QTY, UNIT_TOLERANCE, PCT_TOLERANCE, USE_TOLERANCE_IND, SERVICE_LEVEL_TYPE, STORE_ORDER_MULT, LAST_REVIEW_DATE,
201854, LAST_UPDATE_ID, LAST_UPDATE_DATETIME, TSF_ZERO_SOH_IND, MULT_RUNS_PER_DAY_IND
from rms.REPL_ATTR_UPD_HIST where week_num ='201846';
        
         

set serveroutput on;
set timing on;
 
DECLARE
 
 COUNTER            NUMBER(8)     := 0;
 l_BUYING_SET           rms.uda_values.UDA_ID%type := 5000;  

BEGIN

for k in 0..2 loop    

insert into rms.REPL_ATTR_UPD_HIST 
select rms.REPL_ATTR_UPD_ID_SEQ.nextval, DEPT, CLASS, SUBCLASS, DIFF_AGGREGATE, ITEM, LOC_TYPE, LOCATION, ITEM_PARENT, ITEM_GRANDPARENT, SIZE_PROFILE_IND, 
PRIMARY_REPL_SUPPLIER, ORIGIN_COUNTRY_ID, REVIEW_CYCLE, STOCK_CAT, REPL_ORDER_CTRL, SOURCE_WH, ACTIVATE_DATE, DEACTIVATE_DATE, PRES_STOCK, 
DEMO_STOCK, REPL_METHOD, MIN_STOCK, MAX_STOCK, INCR_PCT, MIN_SUPPLY_DAYS, MAX_SUPPLY_DAYS, TIME_SUPPLY_HORIZON, INV_SELLING_DAYS, SERVICE_LEVEL,
LOST_SALES_FACTOR, REJECT_STORE_ORD_IND, NON_SCALING_IND, MAX_SCALE_VALUE, PICKUP_LEAD_TIME, WH_LEAD_TIME, TERMINAL_STOCK_QTY, SEASON_ID, PHASE_ID, 
PRIMARY_PACK_NO, PRIMARY_PACK_QTY, UNIT_TOLERANCE, PCT_TOLERANCE, USE_TOLERANCE_IND, SERVICE_LEVEL_TYPE, STORE_ORDER_MULT, LAST_REVIEW_DATE,
201850, LAST_UPDATE_ID, LAST_UPDATE_DATETIME, TSF_ZERO_SOH_IND, MULT_RUNS_PER_DAY_IND
from rms.REPL_ATTR_UPD_HIST where week_num ='201846';

end loop;
EXCEPTION
   when OTHERS THEN
      dbms_output.put_line('Exception blcok'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
END;
/
