select REPL_DATE,count(1) from repl_results group by REPL_DATE order by 1;
02-NOV-18	15000
03-NOV-18	15000
04-NOV-18	15000
05-NOV-18	15000
06-NOV-18	15000

     SELECT TO_CHAR(p.vdate - s.repl_results_purge_days,'YYYYMMDD'),
             TO_CHAR(p.vdate - s.repl_results_purge_days + 1, 'YYYYMMDD'),
             TO_CHAR(p.vdate - s.store_orders_purge_days,'YYYYMMDD'),
             TO_CHAR(p.vdate - s.ib_results_purge_days,'YYYYMMDD'),
             TO_CHAR(p.vdate + 14,'YYYYMMDD')
        FROM period p,
             system_options s;
             select repl_results_purge_days from system_options;

20180929	20180930	20181022	20181029	20181112
             
  SELECT *
      FROM all_tab_partitions
     WHERE table_name = 'REPL_RESULTS';
       AND table_name = :ls_table_name
    ORDER BY partition_position;
select vdate-30 from period;
                


select SOURCE_TYPE, STATUS, ORD_TEMP_SEQ_NO, TSF_PO_LINK_NO, ORDER_NO, ALLOC_NO, MASTER_ITEM, ITEM, ITEM_TYPE, DEPT, CLASS, SUBCLASS, BUYER, PACK_QTY, LOC_TYPE, LOCATION, PHYSICAL_WH, PRIMARY_REPL_SUPPLIER, ORIGIN_COUNTRY_ID, POOL_SUPPLIER, SUPP_UNIT_COST, UNIT_COST, ORIG_RAW_ROQ, ORIG_RAW_ROQ_PACK, RAW_ROQ, RAW_ROQ_PACK, PRESCALE_ROQ, ORDER_ROQ, CONTRACT_ROQ, SOURCED_ROQ, LAST_ROUNDED_QTY, LAST_GRP_ROUNDED_QTY, NET_INVENTORY, STOCK_ON_HAND, PACK_COMP_SOH, ON_ORDER, IN_TRANSIT_QTY, PACK_COMP_INTRAN, TSF_RESV_QTY, PACK_COMP_RESV, TSF_EXPECTED_QTY, PACK_COMP_EXP, RTV_QTY, ALLOC_IN_QTY, ALLOC_OUT_QTY, NON_SELLABLE_QTY, ORDER_POINT, ORDER_UP_TO_POINT, SAFETY_STOCK, LOST_SALES, MIN_SUPPLY_DAYS_FORECAST, MAX_SUPPLY_DAYS_FORECAST, TIME_SUPPLY_HORIZON_FORECAST, INV_SELL_DAYS_FORECAST, REVIEW_TIME_FORECAST, ORDER_LEAD_TIME_FORECAST, NEXT_LEAD_TIME_FORECAST, ACCEPTED_STOCK_OUT, ESTIMATED_STOCK_OUT, DUE_IND, REVIEW_TIME, REPL_ORDER_CTRL, REVIEW_CYCLE, STOCK_CAT, SOURCE_WH, ACTIVATE_DATE, DEACTIVATE_DATE, PRES_STOCK, DEMO_STOCK, REPL_METHOD, MIN_STOCK, MAX_STOCK, INCR_PCT, MIN_SUPPLY_DAYS, MAX_SUPPLY_DAYS, TIME_SUPPLY_HORIZON, INV_SELLING_DAYS, SERVICE_LEVEL, LOST_SALES_FACTOR, TERMINAL_STOCK_QTY, SEASON_ID, PHASE_ID, REJECT_STORE_ORD_IND, NON_SCALING_IND, MAX_SCALE_VALUE, SUPP_LEAD_TIME, PICKUP_LEAD_TIME, WH_LEAD_TIME, NEXT_ORDER_LEAD_TIME, COLT_ADDED, NOLT_ADDED, INNER_SIZE, CASE_SIZE, TI, HI, STORE_ORD_MULT, 
REPL_DATE, RECALC_TYPE, RECALC_QTY, AUDSID, NEED_DATE, DELIVERY_SLOT_ID, CURR_ORDER_LEAD_TIME from repl_results;

set serveroutput on;
set timing on;
 
DECLARE
 
 COUNTER            NUMBER(8)     := 0;
 l_BUYING_SET           rms.uda_values.UDA_ID%type := 5000;  

BEGIN

for k in 1..30 loop    

insert into rms.repl_results 
select SOURCE_TYPE, STATUS, ORD_TEMP_SEQ_NO, TSF_PO_LINK_NO, ORDER_NO, ALLOC_NO, MASTER_ITEM, ITEM, ITEM_TYPE, DEPT, CLASS, SUBCLASS, BUYER, PACK_QTY, LOC_TYPE, LOCATION, PHYSICAL_WH, PRIMARY_REPL_SUPPLIER, ORIGIN_COUNTRY_ID, POOL_SUPPLIER, SUPP_UNIT_COST, UNIT_COST, ORIG_RAW_ROQ, ORIG_RAW_ROQ_PACK, RAW_ROQ, RAW_ROQ_PACK, PRESCALE_ROQ, ORDER_ROQ, CONTRACT_ROQ, SOURCED_ROQ, LAST_ROUNDED_QTY, LAST_GRP_ROUNDED_QTY, NET_INVENTORY, STOCK_ON_HAND, PACK_COMP_SOH, ON_ORDER, IN_TRANSIT_QTY, PACK_COMP_INTRAN, TSF_RESV_QTY, PACK_COMP_RESV, TSF_EXPECTED_QTY, PACK_COMP_EXP, RTV_QTY, ALLOC_IN_QTY, ALLOC_OUT_QTY, NON_SELLABLE_QTY, ORDER_POINT, ORDER_UP_TO_POINT, SAFETY_STOCK, LOST_SALES, MIN_SUPPLY_DAYS_FORECAST, MAX_SUPPLY_DAYS_FORECAST, TIME_SUPPLY_HORIZON_FORECAST, INV_SELL_DAYS_FORECAST, REVIEW_TIME_FORECAST, ORDER_LEAD_TIME_FORECAST, NEXT_LEAD_TIME_FORECAST, ACCEPTED_STOCK_OUT, ESTIMATED_STOCK_OUT, DUE_IND, REVIEW_TIME, REPL_ORDER_CTRL, REVIEW_CYCLE, STOCK_CAT, SOURCE_WH, ACTIVATE_DATE, DEACTIVATE_DATE, PRES_STOCK, DEMO_STOCK, REPL_METHOD, MIN_STOCK, MAX_STOCK, INCR_PCT, MIN_SUPPLY_DAYS, MAX_SUPPLY_DAYS, TIME_SUPPLY_HORIZON, INV_SELLING_DAYS, SERVICE_LEVEL, LOST_SALES_FACTOR, TERMINAL_STOCK_QTY, SEASON_ID, PHASE_ID, REJECT_STORE_ORD_IND, NON_SCALING_IND, MAX_SCALE_VALUE, SUPP_LEAD_TIME, PICKUP_LEAD_TIME, WH_LEAD_TIME, NEXT_ORDER_LEAD_TIME, COLT_ADDED, NOLT_ADDED, INNER_SIZE, CASE_SIZE, TI, HI, STORE_ORD_MULT, 
(select vdate-k from period), RECALC_TYPE, RECALC_QTY, AUDSID, NEED_DATE, DELIVERY_SLOT_ID, CURR_ORDER_LEAD_TIME 
from rms.repl_results where trunc(REPL_DATE) ='27-OCT-18' and rownum<='15000';

end loop;
commit;

EXCEPTION
   when OTHERS THEN
      dbms_output.put_line('Exception blcok'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
END;
/


