set serveroutput on;
set timing on;
DECLARE
  counter             NUMBER(10)                    := 0;
  c_commit  	        NUMBER(5)                     := 100;
  
  I_tsf_no            rms.tsfhead.tsf_no%TYPE ;
  n_tsfno            rms.tsfhead.tsf_no%TYPE  ;
  N_CUSTNO            rms.ordcust.ORDCUST_NO%TYPE  ;
  I_create_date       rms.tsfhead.delivery_date%TYPE;
  n_ship              rms.shipment.shipment%TYPE; 
  l_custo_fullfill_no   rms.ordcust.CUSTOMER_ORDER_NO%TYPE; 
  l_EXT_REF_NO          rms.tsfhead.EXT_REF_NO%TYPE;
  
  CURSOR cur_tsf IS
  SELECT tsf_no	from skumar.TSFPRG_MOD sk;
 
BEGIN
   FOR i IN 0..0 LOOP
    
    select vdate-766+i into I_create_date from period;

    FOR k IN cur_tsf LOOP
        I_tsf_no := k.tsf_no;
 
      -- Sequence
      SELECT rms.transfer_number_sequence.NEXTVAL INTO n_tsfno FROM sys.dual;
      SELECT rms.ORDCUST_SEQ.NEXTVAL INTO n_custno FROM sys.dual;
      select n_tsfno||n_custno into l_custo_fullfill_no from sys.dual;
      select n_tsfno||11 into l_EXT_REF_NO from sys.dual;
      SELECT rms.shipment_sequence.nextval INTO n_ship FROM sys.dual;

		  
      -- tsfhead
      INSERT INTO rms.tsfhead (TSF_NO, TSF_PARENT_NO, FROM_LOC_TYPE, FROM_LOC, TO_LOC_TYPE, TO_LOC, EXP_DC_DATE, DEPT, INVENTORY_TYPE, TSF_TYPE, STATUS, FREIGHT_CODE, ROUTING_CODE, CREATE_DATE, CREATE_ID, APPROVAL_DATE, APPROVAL_ID, DELIVERY_DATE, CLOSE_DATE, EXT_REF_NO, REPL_TSF_APPROVE_IND, COMMENT_DESC, EXP_DC_EOW_DATE, MRT_NO, NOT_AFTER_DATE, CONTEXT_TYPE, CONTEXT_VALUE, RESTOCK_PCT, WF_NEED_DATE, DELIVERY_SLOT_ID, ORDER_NO, WF_ORDER_NO, RMA_NO)
         select n_tsfno, TSF_PARENT_NO, FROM_LOC_TYPE, FROM_LOC, TO_LOC_TYPE, TO_LOC, I_create_date, DEPT, INVENTORY_TYPE, TSF_TYPE, 'C', FREIGHT_CODE, ROUTING_CODE, I_create_date, CREATE_ID, I_create_date, APPROVAL_ID, I_create_date, I_create_date, l_EXT_REF_NO, REPL_TSF_APPROVE_IND, COMMENT_DESC, I_create_date, MRT_NO, I_create_date, CONTEXT_TYPE, CONTEXT_VALUE, RESTOCK_PCT, WF_NEED_DATE, DELIVERY_SLOT_ID, ORDER_NO, WF_ORDER_NO, RMA_NO 
            from rms.tsfhead where tsf_no =I_tsf_no;
      
      -- ordcust
      insert into rms.ordcust (ORDCUST_NO, STATUS, ORDER_NO, TSF_NO, SOURCE_LOC_TYPE, SOURCE_LOC_ID, FULFILL_LOC_TYPE, FULFILL_LOC_ID, CUSTOMER_NO, CUSTOMER_ORDER_NO, FULFILL_ORDER_NO, PARTIAL_DELIVERY_IND, DELIVERY_TYPE, CARRIER_CODE, CARRIER_SERVICE_CODE, CONSUMER_DELIVERY_DATE, CONSUMER_DELIVERY_TIME, BILL_FIRST_NAME, BILL_PHONETIC_FIRST, BILL_LAST_NAME, BILL_PHONETIC_LAST, BILL_PREFERRED_NAME, BILL_COMPANY_NAME, BILL_ADD1, BILL_ADD2, BILL_ADD3, BILL_COUNTY, BILL_CITY, BILL_STATE, BILL_COUNTRY_ID, BILL_POST, BILL_JURISDICTION, BILL_PHONE, DELIVER_FIRST_NAME, DELIVER_PHONETIC_FIRST, DELIVER_LAST_NAME, DELIVER_PHONETIC_LAST, DELIVER_PREFERRED_NAME, DELIVER_COMPANY_NAME, DELIVER_ADD1, DELIVER_ADD2, DELIVER_ADD3, DELIVER_COUNTY, DELIVER_CITY, DELIVER_STATE, DELIVER_COUNTRY_ID, DELIVER_POST, DELIVER_JURISDICTION, DELIVER_PHONE, DELIVER_CHARGE, DELIVER_CHARGE_CURR, COMMENTS, CREATE_DATETIME, CREATE_ID, LAST_UPDATE_DATETIME, LAST_UPDATE_ID)
       select n_custno, STATUS, ORDER_NO, n_tsfno, SOURCE_LOC_TYPE, SOURCE_LOC_ID, FULFILL_LOC_TYPE, FULFILL_LOC_ID, CUSTOMER_NO, l_custo_fullfill_no, l_custo_fullfill_no, PARTIAL_DELIVERY_IND, DELIVERY_TYPE, CARRIER_CODE, CARRIER_SERVICE_CODE, I_create_date, CONSUMER_DELIVERY_TIME, BILL_FIRST_NAME, BILL_PHONETIC_FIRST, BILL_LAST_NAME, BILL_PHONETIC_LAST, BILL_PREFERRED_NAME, BILL_COMPANY_NAME, BILL_ADD1, BILL_ADD2, BILL_ADD3, BILL_COUNTY, BILL_CITY, BILL_STATE, BILL_COUNTRY_ID, BILL_POST, BILL_JURISDICTION, BILL_PHONE, DELIVER_FIRST_NAME, DELIVER_PHONETIC_FIRST, DELIVER_LAST_NAME, DELIVER_PHONETIC_LAST, DELIVER_PREFERRED_NAME, DELIVER_COMPANY_NAME, DELIVER_ADD1, DELIVER_ADD2, DELIVER_ADD3, DELIVER_COUNTY, DELIVER_CITY, DELIVER_STATE, DELIVER_COUNTRY_ID, DELIVER_POST, DELIVER_JURISDICTION, DELIVER_PHONE, DELIVER_CHARGE, DELIVER_CHARGE_CURR, COMMENTS, I_create_date, CREATE_ID, I_create_date, LAST_UPDATE_ID
           from rms.ordcust where tsf_no =I_tsf_no;

      -- shipment
      INSERT INTO rms.shipment (SHIPMENT, ORDER_NO, BOL_NO, ASN, SHIP_DATE, RECEIVE_DATE, EST_ARR_DATE, SHIP_ORIGIN, STATUS_CODE, INVC_MATCH_STATUS, INVC_MATCH_DATE, TO_LOC, TO_LOC_TYPE, FROM_LOC, FROM_LOC_TYPE, COURIER, NO_BOXES, EXT_REF_NO_IN, EXT_REF_NO_OUT, COMMENTS, PARENT_SHIPMENT, BILL_TO_LOC, BILL_TO_LOC_TYPE, REF_DOC_NO)
       select n_ship, ORDER_NO, n_tsfno||8787, ASN, I_create_date, I_create_date, I_create_date, SHIP_ORIGIN, STATUS_CODE, INVC_MATCH_STATUS, INVC_MATCH_DATE, TO_LOC, TO_LOC_TYPE, FROM_LOC, FROM_LOC_TYPE, COURIER, NO_BOXES, EXT_REF_NO_IN, l_EXT_REF_NO, COMMENTS, PARENT_SHIPMENT, BILL_TO_LOC, BILL_TO_LOC_TYPE, REF_DOC_NO
               from shipment where shipment in (select shipment from rms.shipSKU where DISTRO_NO =I_tsf_no); 

      INSERT INTO rms.tsfdetail(TSF_NO, TSF_SEQ_NO, ITEM, INV_STATUS, TSF_PRICE, TSF_QTY, FILL_QTY, SHIP_QTY, RECEIVED_QTY, RECONCILED_QTY, DISTRO_QTY, SELECTED_QTY, CANCELLED_QTY, SUPP_PACK_SIZE, TSF_PO_LINK_NO, DEFAULT_CHRGS_2_LEG_IND, MBR_PROCESSED_IND, PUBLISH_IND, TSF_COST, RESTOCK_PCT, FINISHER_AV_RETAIL, FINISHER_UNITS, UPDATED_BY_RMS_IND, CUST_ORD_TSF_UNIT_RETAIL, CUST_ORD_TSF_UNIT_RETAIL_CURR, CUST_ORD_TSF_TOTAL_RETAIL, CUST_ORD_TSF_TOTAL_RETAIL_CURR)
            select n_tsfno, TSF_SEQ_NO, ITEM, INV_STATUS, TSF_PRICE, TSF_QTY, FILL_QTY, SHIP_QTY, RECEIVED_QTY, RECONCILED_QTY, DISTRO_QTY, SELECTED_QTY, CANCELLED_QTY, SUPP_PACK_SIZE, TSF_PO_LINK_NO, DEFAULT_CHRGS_2_LEG_IND, MBR_PROCESSED_IND, PUBLISH_IND, TSF_COST, RESTOCK_PCT, FINISHER_AV_RETAIL, FINISHER_UNITS, UPDATED_BY_RMS_IND, CUST_ORD_TSF_UNIT_RETAIL, CUST_ORD_TSF_UNIT_RETAIL_CURR, CUST_ORD_TSF_TOTAL_RETAIL, CUST_ORD_TSF_TOTAL_RETAIL_CURR 
                from rms.tsfdetail where tsf_no =I_tsf_no;

      INSERT INTO rms.shipsku (SHIPMENT, SEQ_NO, ITEM, DISTRO_NO, DISTRO_TYPE, REF_ITEM, CARTON, INV_STATUS, STATUS_CODE, QTY_RECEIVED, UNIT_COST, UNIT_RETAIL, QTY_EXPECTED, MATCH_INVC_ID, ADJUST_TYPE, ACTUAL_RECEIVING_STORE, RECONCILE_USER_ID, RECONCILE_DATE, TAMPERED_IND, DISPOSITIONED_IND, QTY_MATCHED, WEIGHT_RECEIVED, WEIGHT_RECEIVED_UOM, WEIGHT_EXPECTED, WEIGHT_EXPECTED_UOM, ORIG_MATCHED_COST, INVC_MATCH_STATUS)
            select n_ship, SEQ_NO, ITEM, n_tsfno, DISTRO_TYPE, REF_ITEM, n_tsfno, INV_STATUS, STATUS_CODE, QTY_RECEIVED, UNIT_COST, UNIT_RETAIL, QTY_EXPECTED, MATCH_INVC_ID, ADJUST_TYPE, ACTUAL_RECEIVING_STORE, RECONCILE_USER_ID, RECONCILE_DATE, TAMPERED_IND, DISPOSITIONED_IND, QTY_MATCHED, WEIGHT_RECEIVED, WEIGHT_RECEIVED_UOM, WEIGHT_EXPECTED, WEIGHT_EXPECTED_UOM, ORIG_MATCHED_COST, INVC_MATCH_STATUS
                from shipsku where distro_no =I_tsf_no;

      insert into ordcust_detail (ORDCUST_NO, ITEM, REF_ITEM, ORIGINAL_ITEM, QTY_ORDERED_SUOM, QTY_CANCELLED_SUOM, STANDARD_UOM, TRANSACTION_UOM, SUBSTITUTE_ALLOWED_IND, UNIT_RETAIL, RETAIL_CURRENCY_CODE, COMMENTS, CREATE_DATETIME, CREATE_ID, LAST_UPDATE_DATETIME, LAST_UPDATE_ID)
           select n_custno, ITEM, REF_ITEM, ORIGINAL_ITEM, QTY_ORDERED_SUOM, QTY_CANCELLED_SUOM, STANDARD_UOM, TRANSACTION_UOM, SUBSTITUTE_ALLOWED_IND, UNIT_RETAIL, RETAIL_CURRENCY_CODE, COMMENTS, I_create_date, CREATE_ID, I_create_date, LAST_UPDATE_ID
               from ordcust_detail where ORDCUST_NO  in (select ORDCUST_NO from ordcust where tsf_no =I_tsf_no);

     delete from tsf_mfqueue where tsf_no = n_tsfno;
	 delete from TRANSFERS_PUB_INFO where tsf_no = n_tsfno;
       insert into TRANSFERS_PUB_INFO (TSF_NO, TSF_TYPE, INITIAL_APPROVAL_IND, THREAD_NO, PHYSICAL_FROM_LOC, FROM_LOC, FROM_LOC_TYPE, PHYSICAL_TO_LOC, TO_LOC, TO_LOC_TYPE, FREIGHT_CODE, PUBLISHED)
        select n_tsfno, TSF_TYPE, INITIAL_APPROVAL_IND, THREAD_NO, PHYSICAL_FROM_LOC, FROM_LOC, FROM_LOC_TYPE, PHYSICAL_TO_LOC, TO_LOC, TO_LOC_TYPE, FREIGHT_CODE, PUBLISHED
        from TRANSFERS_PUB_INFO where tsf_no =I_tsf_no;
     
   --   dbms_output.put_line('Tsf_no '||n_tsfno);
     
     
	  END LOOP;
	  END LOOP;
	commit;
  
EXCEPTION
 
   when OTHERS THEN
      dbms_output.put_line('Exception block'||dbms_utility.FORMAT_ERROR_BACKTRACE||dbms_utility.format_error_stack);
      ROLLBACK;
 
END;
/